//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Entity
{
    using Core.EntityModel;
    using Core.Interfaces.DbContext;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Forum_dbEntities : DbContext, IForumtDbContext
    {
        public Forum_dbEntities()
            : base("name=Forum_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Banned> Banneds { get; set; }
    }
}
