//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.EntityModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class User
    {
        public User()
        {
            this.Messages = new HashSet<Message>();
            this.Topics = new HashSet<Topic>();
            this.Banneds = new HashSet<Banned>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }

        [Required]
        public string Login { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string Email { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string MessagesCount { get; set; }
        public string Image { get; set; }
        public string Country { get; set; }
        public int StatusID { get; set; }
        public int RoleID { get; set; }
        public string VK { get; set; }
        public string ICQ { get; set; }
        public string Skype { get; set; }
        public bool IsBanned { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Role Role { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }
        public virtual ICollection<Banned> Banneds { get; set; }
    }
}
